### ISSUE TITLE
Quiet SiZer::SiZer Printing

### ISSUE THREAD

**Issue by njlyon0** [dereksonderegger/SiZer#1]
First off, this package is really useful and thanks so much for making it! I do have a quick request though if it it would not be too much trouble

I am using the `SiZer::SiZer` function inside of a loop where I've specified `h = c(2, 10)` to check a variety of bandwidths for each iteration of the loop. Because `SiZer` (the function) `print`s  each bandwidth as it uses it internally you can imagine that my loop is very talkative.

I think changing `print()` to `message()` in [line 85 of the SiZer script](https://github.com/dereksonderegger/SiZer/blob/master/R/SiZer.R#L85) would be an improvement because it would allow `suppressMessages()` to stop `SiZer` from returning so much content in the Console when it isn't necessary.

Alternatively I suppose you could include an argument for whether the user wants the function to run quietly or not but that feels like it would be more work on your end.

Thanks again for a great function and feel free to message me if something in this Issue is unclear!

**Comment by dereksonderegger** [comment]
This makes a lot of sense. I added a `quiet` option to `SiZer` with a default of TRUE. I also wanted a ggplot2 option to the plot function as well as an `as.data.frame()` function. I've uploaded the updated version here to GitHub and have submitted to CRAN. It might be a day or two before it shows up on CRAN but you can download it from GitHub using:

    devtools::install_github('dereksonderegger/SiZer')

**Comment by njlyon0** [comment]
Thanks so much! Those modifications are *awesome* and I'll be sure to keep an eye out for when the updated version hits CRAN.
